---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
        region: 'us-east-2'

  vars:
    ig_pw: "{{ ig_pass }}"
    ig_secret: {
                "username": "image_gallery",
                "password": "{{ ig_pw }}",
                "engine": "postgres",
                "host": "{{ rds_restored.instance.endpoint }}",
                "port": 5432,
                "dbInstanceIdentifier": "m5ig-db",
                "database_name": "image_gallery"
              }

  tasks:
    - name: Add ig user to Secrets Manager
      aws_secret:
        name: 'm5-ig-secret'
        state: present
        secret_type: 'string'
        secret: '{{ ig_secret | to_json }}'
