# Creates the vpc and subnets
---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
        region: 'us-east-2'

  tasks:
    - name: Create VPC
      ec2_vpc_net:
        name: mod5vpc
        cidr_block: 10.10.0.0/16
        tags:
          Name: mod5vpc
          Module: 5
        state: present
      register: vpc


    - name: Create Public Subnet 1
      ec2_vpc_subnet:
        vpc_id: '{{ vpc.vpc.id }}'
        tags:
          Name: mod5publicsn1
          Module: 5
        cidr: 10.10.0.0/24
        az: 'us-east-2a'
        state: present
      register: public_sn_1

    - name: Create Private Subnet 1
      ec2_vpc_subnet:
        vpc_id: '{{ vpc.vpc.id }}'
        tags:
          Name: mod5privatesn1
          Module: 5
        cidr: 10.10.1.0/24
        az: 'us-east-2a'
        state: present
      register: private_sn_1

    - name: Create Private Subnet 2
      ec2_vpc_subnet:
        vpc_id: '{{ vpc.vpc.id }}'
        tags:
          Name: mod5privatesn2
          Module: 5
        cidr: 10.10.2.0/24
        az: 'us-east-2b'
        state: present
      register: private_sn_2

    - name: Create Public Subnet 2
      ec2_vpc_subnet:
        vpc_id: '{{ vpc.vpc.id }}'
        tags:
          Name: mod5publicsn2
          Module: 5
        cidr: 10.10.3.0/24
        az: 'us-east-2b'
        state: present
      register: public_sn_2
